#!/bin/sh
# Convert a text file with abc musical notation (abcnotation.com)
# to a PDF, using abc2ps.
TMPPS=$(mktemp /tmp/temp.XXXXXXX).ps
PDF=$(basename "${1%.abc}.pdf")
abcm2ps "$@" -q -x -N3 -O $TMPPS
abcmaddidx.tcl -nx $TMPPS $TMPPS-index
ps2pdf $TMPPS-index $PDF
rm $TMPPS $TMPPS-index
