#!/bin/sh
# Convert a text file with abc musical notation (abcnotation.com)
# to a PDF, using abc2ps.
TMPPS=$(mktemp /tmp/temp.XXXXXXX).ps
PDF=$(basename "${1%.abc}.pdf")
abcm2ps "$@" -q -x -O $TMPPS
abcmaddidx.tcl -b index-$TMPPS
ps2pdf index-$TMPPS $PDF
#echo "Created $PDF"
rm $TMPPS
