#!/bin/bash -xv

if [ $# -ne 1 ]
then
    echo "Usage: $0 <archive_directory>"
    exit
fi

ARCHIVEDIR=$1

SOURCEDIR="~GitHub/${ARCHIVEDIR}"
SITEDIR="~GitHub/${ARCHIVEDIR}/_site/abc-collections"


#
# Get any updates from main respository
#
cd ${SOURCEDIR}
/usr/local/bin/git pull

#
# Build the ABC source files in ${SITEDIR}
#
/usr/local/bin/jekyll build
if [ $? -ne 0 ]
then
    exit
fi

cd ${SITEDIR}
ABCFILES=`ls *abc`

#
# Build the PDF files in ${SOURCEDIR}
#
cd ${SOURCEDIR}/abc-collections

for ABCFILE in ${ABCFILES}
do
    ${SOURCEDIR}/_scripts/abc2pdf ${SITEDIR}/${ABCFILE}
done

cd ${SOURCEDIR}
#
# Push the new PDFs to the main site
# They'll get loaded next time there's an upgrade
#
/usr/local/bin/git add .
/usr/local/bin/git commit -m "Updating Tunebook PDFs"
/usr/local/bin/git push
